import type { Locale } from './i18n';

const adminMessages = {
  en: {
    brand: {
      name: 'ClawScale Admin',
      tagline: 'Operations shell',
    },
    layout: {
      title: 'Admin console',
      signOutTitle: 'Sign out',
      nav: [
        { href: '/admin/dashboard', label: 'Dashboard', exact: false },
        { href: '/admin/customers', label: 'Chat records', exact: false },
        { href: '/admin/shared-channels', label: 'Shared channels', exact: false },
        { href: '/admin/deliveries', label: 'Deliveries', exact: false },
        { href: '/admin/admins', label: 'Admins', exact: false },
      ],
      roleLabel: 'Admin account',
    },
    common: {
      loading: 'Loading...',
      errorPrefix: 'Error',
      empty: 'No records found.',
      retry: 'Retry',
      cancel: 'Cancel',
      close: 'Close',
      readOnly: 'Read-only',
      readOnlyDescription: 'Operational reference only. Changes stay on the API side for now.',
    },
    paging: {
      previous: 'Previous',
      next: 'Next',
      summary: (from: number, to: number, total: number) => 'Showing ' + from + '-' + to + ' of ' + total,
    },
    login: {
      title: 'Admin sign in',
      description: 'Use an AdminAccount to access the admin backend MVP.',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      submit: 'Sign in',
      submitting: 'Signing in...',
      genericError: 'We could not sign you in right now.',
      invalidCredentials: 'The AdminAccount email or password is incorrect.',
      inactiveAccount: 'This AdminAccount is inactive.',
    },
    dashboard: {
      title: 'Dashboard',
      subtitle: 'Active customers, chat volume, and runtime queue status.',
      actions: {
        chatRecords: 'View chat records',
        sharedChannels: 'Manage shared channels',
      },
      cards: {
        activeToday: 'Active today',
        activeWeek: 'Active this week',
        activeMonth: 'Active this month',
        messagesToday: 'Messages today',
        totalCustomers: 'Total customers',
        queuedInbounds: 'Queued inbounds',
      },
      sections: {
        messageBreakdown: 'Message breakdown',
        operations: 'Operations',
      },
      fields: {
        userMessagesToday: 'User messages today',
        assistantMessagesToday: 'Assistant messages today',
        messagesWeek: 'Messages this week',
        messagesMonth: 'Messages this month',
        totalMessages: 'Total messages',
        lastMessageAt: 'Latest message',
        conversations: 'Conversations',
        channels: 'Channels',
        connectedChannels: 'Connected channels',
        readyBindings: 'Ready bindings',
        pendingBindings: 'Pending bindings',
        errorBindings: 'Error bindings',
      },
    },
    customers: {
      title: 'Chat records',
      subtitle: 'Users ordered by latest chat activity for admin review.',
      columns: {
        customer: 'Customer',
        lastMessage: 'Last message',
        messageCount: 'Messages',
        contactIdentifier: 'Contact identifier',
        claimStatus: 'Claim status',
        parkedInbounds: 'Parked inbounds',
        registered: 'Registered',
        firstSeen: 'First seen',
        agent: 'Agent',
        channels: 'Channels',
      },
    },
    channels: {
      title: 'Channels',
      subtitle: 'Read-only customer channel inventory with admin filters.',
      filters: {
        status: 'Status',
        kind: 'Kind',
        allStatuses: 'All statuses',
        allKinds: 'All kinds',
      },
      columns: {
        name: 'Channel',
        kind: 'Kind',
        status: 'Status',
        customerId: 'Customer ID',
        updated: 'Updated',
      },
    },
    deliveries: {
      title: 'Failed deliveries',
      subtitle: 'Recent failed outbound deliveries only.',
      filters: {
        channelId: 'Channel ID',
        apply: 'Apply filter',
        clear: 'Clear',
      },
      columns: {
        delivery: 'Delivery',
        tenantId: 'Tenant',
        channelId: 'Channel',
        idempotencyKey: 'Idempotency key',
        error: 'Error',
        updated: 'Updated',
      },
    },
    agents: {
      title: 'Agents',
      subtitle: 'Single-agent operational record for Coke.',
      fields: {
        slug: 'Slug',
        endpoint: 'Endpoint',
        tokenConfigured: 'Token configured',
        defaultAgent: 'Default agent',
        healthStatus: 'Handshake health',
        healthSource: 'Health source',
        observedAt: 'Observed at',
        createdAt: 'Created',
        updatedAt: 'Updated',
      },
    },
    admins: {
      title: 'Admins',
      subtitle: 'Manage AdminAccount access to the admin backend MVP.',
      addAdmin: 'Add admin',
      addTitle: 'Create admin account',
      emailLabel: 'Admin email',
      passwordLabel: 'Temporary password',
      createSubmit: 'Create admin',
      removeTitle: 'Remove admin',
      confirmRemove: 'Remove this admin account?',
      genericError: 'The admin change could not be completed.',
      columns: {
        email: 'Email',
        status: 'Status',
        createdAt: 'Created',
        updatedAt: 'Updated',
        actions: 'Actions',
      },
      statusLabels: {
        active: 'Active',
        inactive: 'Inactive',
      },
    },
    sharedChannels: {
      title: 'Shared channels',
      subtitle: 'Create, configure, connect, and retire platform-owned shared channels.',
      openCreate: 'Create shared channel',
      createTitle: 'Create shared channel',
      detailTitle: 'Shared channel',
      fields: {
        name: 'Name',
        kind: 'Kind',
        agentId: 'Agent ID',
        config: 'Config JSON',
        instanceName: 'Instance name',
        fromNumber: 'From number',
        webhookToken: 'Webhook token',
        signingSecret: 'Signing secret',
        webhookSubscriptionId: 'Webhook subscription',
      },
      actions: {
        save: 'Save changes',
        connect: 'Connect channel',
        disconnect: 'Disconnect channel',
        retire: 'Retire shared channel',
        back: 'Back to shared channels',
      },
      confirmRetire: 'Retire this shared channel?',
      instanceNameHelp: 'Used for Evolution webhook registration and message delivery.',
      instanceNameLocked: 'Disconnect the channel before changing the instance name.',
      fromNumberHelp: 'Defaults to LINQ_FROM_NUMBER when left blank.',
      fromNumberLocked: 'Disconnect before changing the Linq sender number.',
      webhookTokenHidden: 'Hidden and managed server-side.',
      signingSecretHidden: 'Hidden and managed server-side.',
      columns: {
        name: 'Channel',
        kind: 'Kind',
        status: 'Status',
        agent: 'Agent',
        updated: 'Updated',
      },
    },
  },
  zh: {
    brand: {
      name: 'ClawScale 管理后台',
      tagline: '运维控制台',
    },
    layout: {
      title: '管理控制台',
      signOutTitle: '退出登录',
      nav: [
        { href: '/admin/dashboard', label: '看板', exact: false },
        { href: '/admin/customers', label: '聊天记录', exact: false },
        { href: '/admin/shared-channels', label: '共享渠道', exact: false },
        { href: '/admin/deliveries', label: '投递', exact: false },
        { href: '/admin/admins', label: '管理员', exact: false },
      ],
      roleLabel: '管理员账号',
    },
    common: {
      loading: '加载中...',
      errorPrefix: '错误',
      empty: '暂无记录。',
      retry: '重试',
      cancel: '取消',
      close: '关闭',
      readOnly: '只读',
      readOnlyDescription: '当前仅提供运维查看，修改操作仍通过 API 处理。',
    },
    paging: {
      previous: '上一页',
      next: '下一页',
      summary: (from: number, to: number, total: number) => '显示 ' + from + '-' + to + ' / ' + total,
    },
    login: {
      title: '管理员登录',
      description: '使用 AdminAccount 访问管理后台 MVP。',
      emailLabel: '邮箱',
      passwordLabel: '密码',
      submit: '登录',
      submitting: '登录中...',
      genericError: '暂时无法登录，请稍后再试。',
      invalidCredentials: '管理员邮箱或密码不正确。',
      inactiveAccount: '该管理员账号已停用。',
    },
    dashboard: {
      title: '数据看板',
      subtitle: '查看活跃用户、聊天量和运行队列状态。',
      actions: {
        chatRecords: '查看聊天记录',
        sharedChannels: '管理共享渠道',
      },
      cards: {
        activeToday: '今日活跃',
        activeWeek: '本周活跃',
        activeMonth: '本月活跃',
        messagesToday: '今日消息',
        totalCustomers: '用户总数',
        queuedInbounds: '待处理入站',
      },
      sections: {
        messageBreakdown: '消息明细',
        operations: '运行状态',
      },
      fields: {
        userMessagesToday: '今日用户消息',
        assistantMessagesToday: '今日助手消息',
        messagesWeek: '本周消息',
        messagesMonth: '本月消息',
        totalMessages: '总消息数',
        lastMessageAt: '最新消息',
        conversations: '会话数',
        channels: '渠道数',
        connectedChannels: '已连接渠道',
        readyBindings: '已就绪绑定',
        pendingBindings: '处理中绑定',
        errorBindings: '异常绑定',
      },
    },
    customers: {
      title: '聊天记录',
      subtitle: '按最新聊天时间倒序展示用户，方便管理员审查。',
      columns: {
        customer: '客户',
        lastMessage: '最新聊天',
        messageCount: '消息数',
        contactIdentifier: '联系标识',
        claimStatus: '认领状态',
        parkedInbounds: '待处理入站',
        registered: '注册时间',
        firstSeen: '首次出现',
        agent: '代理',
        channels: '渠道',
      },
    },
    channels: {
      title: '渠道',
      subtitle: '带筛选的客户渠道只读清单。',
      filters: {
        status: '状态',
        kind: '类型',
        allStatuses: '全部状态',
        allKinds: '全部类型',
      },
      columns: {
        name: '渠道',
        kind: '类型',
        status: '状态',
        customerId: '客户 ID',
        updated: '更新时间',
      },
    },
    deliveries: {
      title: '失败投递',
      subtitle: '仅展示最近失败的 OutboundDelivery 记录。',
      filters: {
        channelId: '渠道 ID',
        apply: '应用筛选',
        clear: '清除',
      },
      columns: {
        delivery: '投递',
        tenantId: '租户',
        channelId: '渠道',
        idempotencyKey: '幂等键',
        error: '错误',
        updated: '更新时间',
      },
    },
    agents: {
      title: '代理',
      subtitle: 'Coke 单代理运维记录。',
      fields: {
        slug: 'Slug',
        endpoint: 'Endpoint',
        tokenConfigured: '已配置令牌',
        defaultAgent: '默认代理',
        healthStatus: '握手健康',
        healthSource: '健康来源',
        observedAt: '观察时间',
        createdAt: '创建时间',
        updatedAt: '更新时间',
      },
    },
    admins: {
      title: '管理员',
      subtitle: '管理 AdminAccount 对后台 MVP 的访问。',
      addAdmin: '新增管理员',
      addTitle: '创建管理员账号',
      emailLabel: '管理员邮箱',
      passwordLabel: '临时密码',
      createSubmit: '创建管理员',
      removeTitle: '移除管理员',
      confirmRemove: '确认移除此管理员账号？',
      genericError: '管理员操作失败。',
      columns: {
        email: '邮箱',
        status: '状态',
        createdAt: '创建时间',
        updatedAt: '更新时间',
        actions: '操作',
      },
      statusLabels: {
        active: '启用',
        inactive: '停用',
      },
    },
    sharedChannels: {
      title: '共享渠道',
      subtitle: '创建、配置、连接并退役平台级共享渠道。',
      openCreate: '创建共享渠道',
      createTitle: '创建共享渠道',
      detailTitle: '共享渠道',
      fields: {
        name: '名称',
        kind: '类型',
        agentId: '代理 ID',
        config: '配置 JSON',
        instanceName: '实例名',
        fromNumber: '发送号码',
        webhookToken: 'Webhook 令牌',
        signingSecret: '签名密钥',
        webhookSubscriptionId: 'Webhook 订阅',
      },
      actions: {
        save: '保存修改',
        connect: '连接通道',
        disconnect: '断开通道',
        retire: '退役共享渠道',
        back: '返回共享渠道列表',
      },
      confirmRetire: '确认退役这个共享渠道？',
      instanceNameHelp: '用于 Evolution webhook 注册和消息发送。',
      instanceNameLocked: '先断开通道，再修改实例名。',
      fromNumberHelp: '留空时使用 LINQ_FROM_NUMBER。',
      fromNumberLocked: '断开 Linq 通道后才能修改发送号码。',
      webhookTokenHidden: '已隐藏，由后端代管。',
      signingSecretHidden: '已隐藏，由服务器端管理。',
      columns: {
        name: '渠道',
        kind: '类型',
        status: '状态',
        agent: '代理',
        updated: '更新时间',
      },
    },
  },
} as const;

export function getAdminCopy(locale: Locale) {
  return adminMessages[locale];
}
